import test from 'node:test';
import assert from 'node:assert/strict';
import {analyzeReply,modelHealth,outcomes,summary,wilson,learningRecommendation,chooseVariant,trainingExamples,cleanReply} from '../lib/learning.ts';
const now=Date.parse('2026-09-22T18:00:00Z');
function workspace():any{return {contacts:[{id:'c',company:'Current Co',industry:'Finance'}],messages:[{id:'m',contactId:'c',subject:'Test',body:'Hi there',state:'sent',sentAt:'2026-09-01T10:00:00Z',sequence:0,variant:'workflow-question',companyAtSend:'Original Co',recipientTimezone:'America/Chicago'}],conversations:[],meetings:[]};}
function reply(p:any={}):any{return {id:'r',contactId:'c',messageId:'m',body:'Happy to share',classification:'Interested',receivedAt:'2026-09-02T10:00:00Z',reviewed:true,...p};}
test('denominators exclude drafts, uncertain, followups, future and synthetic sends',()=>{const w=workspace();for(const [i,state] of ['draft','queued','uncertain'].entries())w.messages.push({...w.messages[0],id:'bad'+i,contactId:'bad'+i,state});w.messages.push({...w.messages[0],id:'s',contactId:'s',synthetic:true},{...w.messages[0],id:'f',contactId:'f',sequence:1});assert.equal(outcomes(w,now).length,1);});
test('reply linkage, chronology, review and automation govern human outcomes',()=>{const w=workspace();w.conversations=[reply({reviewed:false}),reply({id:'unlinked',messageId:''}),reply({id:'old',receivedAt:'2026-08-01'}),reply({id:'late',receivedAt:'2026-09-20'}),reply({id:'ooo',classification:'Out of office'})];assert.equal(summary(outcomes(w,now)).human,0);w.conversations.push(reply());assert.equal(summary(outcomes(w,now)).positive,1);w.conversations.push(reply({id:'duplicate'}));assert.equal(summary(outcomes(w,now)).positive,1)});
test('first contact selection precedes range filtering; duplicates do not re-enroll',()=>{const w=workspace();w.messages[0].sentAt='2026-01-01';w.messages.push({...w.messages[0],id:'duplicate',sentAt:'2026-09-01'});assert.equal(outcomes(w,now,90).length,0)});
test('maturity, frozen company, bookings and bounce denominators are explicit',()=>{const w=workspace();w.meetings=[{contactId:'c',state:'Upcoming',createdAt:'2026-09-04'}];let r=outcomes(w,now)[0];assert.equal(r.company,'Original Co');assert.equal(r.booked,true);assert.equal(r.mature,true);w.messages[0].state='bounced';assert.equal(summary(outcomes(w,now)).n,1);assert.equal(summary(outcomes(w,now)).bounces,1);w.messages[0].sentAt='2026-09-20';assert.equal(outcomes(w,now)[0].mature,false)});
test('Wilson intervals remain honest for zero or tiny samples',()=>{assert.deepEqual(wilson(0,0),{low:0,high:1});assert.ok(wilson(1,1).low<.3);assert.ok(wilson(0,10).high>.2)});
test('no winner from tiny samples; assignment remains balanced',()=>{const w=workspace();w.conversations=[reply()];assert.equal(learningRecommendation(w,now).preferred,null);assert.equal(chooseVariant(w,now,.1).variant,'workflow-question');assert.equal(chooseVariant(w,now,.9).variant,'career-lesson')});
test('reply classifier prioritizes opt-out and ignores quoted original emails',()=>{assert.equal(analyzeReply('Happy to help but please remove me from your list').label,'Opt-out');assert.equal(analyzeReply('No thank you\n> Happy to help').label,'Declined');assert.equal(analyzeReply('Interesting thought, perhaps.').label,'Ambiguous');assert.equal(cleanReply('Actual text\nOn Monday Alice wrote:\nquoted'),'Actual text');});
test('training excludes synthetic/unreviewed/duplicate examples and starts cold',()=>{const rs=[reply(),reply({id:'x'}),reply({id:'y',body:'different',synthetic:true}),reply({id:'z',body:'other',reviewed:false})];assert.equal(trainingExamples(rs).length,1);assert.equal(modelHealth(rs).ready,false);});
test('Naive Bayes fits reviewed labels and measures a chronological holdout',()=>{const rs=Array.from({length:60},(_,i)=>reply({id:''+i,body:(i%2?'delighted share insight expertise':'unavailable decline assistance')+' example '+String.fromCharCode(97+i%26)+String.fromCharCode(97+Math.floor(i/26)),classification:i%2?'Interested':'Declined',receivedAt:new Date(Date.parse('2026-01-01')+i*86400000).toISOString()}));const health=modelHealth(rs);assert.equal(health.samples,60);assert.equal(health.testSize,12);assert.equal(health.accuracy,1);assert.equal(health.ready,true);assert.equal(analyzeReply('delighted share expertise insight',rs).method,'multinomial-naive-bayes-v1');});
