import {defaults,type Workspace,type Contact} from './types';
const names=[['Maya Chen','Equity Sales Analyst','Northstar Securities','Sales & Trading','New York, NY','how institutional equity sales supports clients'],['Daniel Okafor','Associate, Rates Trading','Meridian Capital','Sales & Trading','New York, NY','how a rates desk manages client flow'],['Sofia Ramirez','Senior Consultant','Fieldwork Partners','Consulting','Chicago, IL','turning research into strategic decisions'],['James Park','Engineering Manager','Forma','Technology','Seattle, WA','moving from engineering into leadership'],['Amara Williams','Research Scientist','Helio Energy','Climate','Boston, MA','bringing clean-energy research to market'],['Oliver Bennett','Head of Design','Studio Relay','Design','London, UK','leading cross-functional design teams']];
export const demo:Workspace={demo:true,settings:{...defaults,name:'Alex Morgan',intro:'I’m Alex, a university student exploring how thoughtful teams solve complex problems.',goal:'how people make the transition from studying a field to contributing to it',signature:'Alex Morgan',interests:'Product, climate, and thoughtful technology'},contacts:names.map((n,i)=>({id:'demo-'+i,name:n[0],title:n[1],company:n[2],industry:n[3],location:n[4],email:n[0].split(' ')[0].toLowerCase()+'@example.com',linkedin:'',timezone:i===5?'Europe/London':'America/Chicago',status:['Ready for review','Draft ready','Replied','Meeting booked','Research needed','Ready for review'][i],verification:i===4?'catch-all':'valid',verifiedAt:'2026-09-22',emailOrigin:'published',identityConfirmed:true,fit:`Your work at ${n[2]} connects directly to my interest in ${n[5]}.`,topic:n[5],notes:'Synthetic example. This person, company, and research are fictional.',sources:[{url:'https://example.com/professional-bio',note:'Demonstration research only; not a real source.',retrievedAt:'2026-09-22'}],synthetic:true} as Contact)),messages:[],meetings:[{id:'meeting-demo',contactId:'demo-3',title:'An introduction with James',start:'2026-09-24T15:00:00-05:00',state:'Upcoming',notes:'Synthetic meeting. No calendar event exists.',synthetic:true}],conversations:[{id:'reply-demo',contactId:'demo-2',body:'Happy to chat! I’d enjoy sharing a little about the transition into consulting. Would next week work for you?',classification:'Interested',receivedAt:'2026-09-22T09:00:00-05:00',synthetic:true}],events:[{id:'activity-demo',type:'Demonstration workspace opened',data:{detail:'All people and activity shown here are synthetic.'},created:'2026-09-22T09:00:00-05:00'}]};
demo.messages=demo.contacts.slice(0,3).map((c,i)=>({id:'draft-demo-'+i,contactId:c.id,subject:`Learning about ${c.industry.toLowerCase()}`,body:`Hi ${c.name.split(' ')[0]},\n\nI’m Alex, a university student exploring a career in ${c.industry.toLowerCase()}. I’m curious about ${c.topic}, which is what drew me to your work at ${c.company}.\n\nI’d especially love to understand which experiences shaped your approach, and what you wish you’d known when starting out. Hearing how those lessons show up in your day-to-day work would help me think more carefully about the experiences I pursue next.\n\nWhat is one part of your day-to-day work that someone exploring the field might not expect? I’d appreciate any perspective you’re open to sharing. No worries if your schedule is full.\n\nAlex`,state:'waiting_approval',scheduledAt:'',sequence:0,synthetic:true}));

// Synthetic sent history for inspecting the Statistics UI; never used for live learning.
for(let i=2;i<6;i++){const c=demo.contacts[i];demo.messages.push({id:'sent-demo-'+i,contactId:c.id,subject:'A question about your experience',body:'A fictional initial email asking about professional experience, with no booking request.',state:'sent',scheduledAt:'',sentAt:'2026-09-05T15:00:00Z',sequence:0,variant:i%2?'career-lesson':'workflow-question',sentEvidence:'manual',companyAtSend:c.company,industryAtSend:c.industry,locationAtSend:c.location,recipientTimezone:c.timezone,synthetic:true});}
demo.conversations[0]={...demo.conversations[0],messageId:'sent-demo-2',receivedAt:'2026-09-08T14:00:00Z',reviewed:true};
demo.conversations.push({id:'decline-demo',contactId:'demo-5',messageId:'sent-demo-5',body:'Thank you for reaching out, but I am unable to help at the moment.',classification:'Declined',receivedAt:'2026-09-09T14:00:00Z',reviewed:true,synthetic:true});
demo.meetings[0].createdAt='2026-09-10T15:00:00Z';
