import type {Workspace, Conversation, Message} from './types';
export const CLASSES=['Interested','Human reply','Declined','Opt-out','Referral','Out of office','Delivery notice','Contact later','Ambiguous'];
export const VARIANTS=['workflow-question','career-lesson'] as const;
const HUMAN=new Set(['Interested','Human reply','Declined','Opt-out','Referral','Contact later']);
const DAY=86400000;
export function cleanReply(body:string){return body.split(/\nOn .{1,200}wrote:|\nFrom:|\n-{2,}\s*Original Message/i)[0].split('\n').filter(x=>!x.trim().startsWith('>')).join('\n').slice(0,12000);}
function tokens(text:string){return cleanReply(text).toLowerCase().replace(/https?:\/\/\S+|\S+@\S+/g,' ').match(/[a-z]{2,24}/g)?.slice(0,1500)||[];}
function train(examples:Conversation[]){const vocabulary=new Set<string>();const classes=new Map<string,{docs:number;total:number;words:Map<string,number>}>();for(const e of examples){const c=classes.get(e.classification)||{docs:0,total:0,words:new Map<string,number>()};c.docs++;for(const word of tokens(e.body)){vocabulary.add(word);c.words.set(word,(c.words.get(word)||0)+1);c.total++;}classes.set(e.classification,c);}return {classes,vocabulary,n:examples.length};}
function predict(model:ReturnType<typeof train>,body:string){const words=tokens(body).filter(w=>model.vocabulary.has(w));if(!words.length||model.classes.size<2)return null;const ranked=[...model.classes].map(([label,c])=>({label,score:Math.log(c.docs/model.n)+words.reduce((sum,w)=>sum+Math.log(((c.words.get(w)||0)+1)/(c.total+model.vocabulary.size)),0)})).sort((a,b)=>b.score-a.score);return {label:ranked[0].label,margin:ranked[0].score-ranked[1].score};}
export function trainingExamples(replies:Conversation[]){const seen=new Set<string>();return replies.filter(r=>r.reviewed&&!r.synthetic&&CLASSES.includes(r.classification)&&r.classification!=='Ambiguous').sort((a,b)=>a.receivedAt.localeCompare(b.receivedAt)).filter(r=>{const key=cleanReply(r.body).toLowerCase().trim();if(!key||seen.has(key))return false;seen.add(key);return true;}).slice(-500);}
export function modelHealth(replies:Conversation[]){const samples=trainingExamples(replies);if(samples.length<40)return {samples:samples.length,ready:false,accuracy:null as number|null,testSize:0,reason:'Needs 40 distinct, human-reviewed replies; suggestions remain rules-based.'};const split=Math.floor(samples.length*.8),fit=samples.slice(0,split),test=samples.slice(split);const model=train(fit);const counts=[...model.classes.values()].map(c=>c.docs);if(counts.length<2||Math.min(...counts)<5)return {samples:samples.length,ready:false,accuracy:null,testSize:test.length,reason:'Needs at least two reply categories with five training examples each.'};const accuracy=test.filter(r=>predict(model,r.body)?.label===r.classification).length/test.length;const majority=[...model.classes].sort((a,b)=>b[1].docs-a[1].docs)[0][0];const baseline=test.filter(r=>r.classification===majority).length/test.length;const labels=[...new Set(test.map(r=>r.classification))];const recallOk=labels.length>=2&&labels.every(label=>{const subset=test.filter(r=>r.classification===label);return subset.filter(r=>predict(model,r.body)?.label===label).length/subset.length>=.5});const ready=accuracy>=.7&&accuracy>=baseline+.05&&recallOk;return {samples:samples.length,ready,accuracy,testSize:test.length,reason:ready?'Naive Bayes suggestions enabled. Every label still requires review.':'Validation does not beat the majority baseline with adequate category recall; ML suggestions disabled.'};}
export function analyzeReply(body:string,replies:Conversation[]=[]){const text=cleanReply(body).toLowerCase();const rules:[RegExp,string,string][]=[[/\b(unsubscribe|remove me|stop (emailing|contacting)|do not contact|don't contact)\b/,'Opt-out','Explicit request to stop contact'],[/\b(undeliverable|delivery status notification|address not found|mailer-daemon)\b/,'Delivery notice','Delivery-system wording'],[/\b(out of (the )?office|automatic reply|auto.?reply|on leave|on vacation)\b/,'Out of office','Possible automatic absence response'],[/\b(not interested|no thank you|unable to help|cannot help)\b/,'Declined','Possible decline'],[/\b(reach out|contact me|check back)\b.{0,40}\b(later|next month|next quarter)\b/,'Contact later','Possible request to reconnect later'],[/\b(happy to (chat|help|share)|glad to (chat|help)|would love to)\b/,'Interested','Possible positive response'],[/\b(recommend (contacting|reaching)|my colleague|refer you)\b/,'Referral','Possible referral']];for(const [pattern,label,reason] of rules)if(pattern.test(text))return {label,method:'rules-v1',reason,needsReview:true};const health=modelHealth(replies);if(health.ready){const result=predict(train(trainingExamples(replies)),body);if(result&&result.margin>=2)return {label:result.label,method:'multinomial-naive-bayes-v1',reason:'Learned from your reviewed replies; model score is not a calibrated probability.',needsReview:true};}return {label:'Ambiguous',method:'abstain',reason:'Not enough reliable evidence to classify. Please review.',needsReview:true};}
export function wilson(k:number,n:number){if(!n)return {low:0,high:1};const z=1.96,p=k/n,d=1+z*z/n,center=(p+z*z/(2*n))/d,half=z*Math.sqrt((p*(1-p)+z*z/(4*n))/n)/d;return {low:Math.max(0,center-half),high:Math.min(1,center+half)};}
export type Outcome={message:Message;replies:Conversation[];human:boolean;positive:boolean;declined:boolean;optout:boolean;bounce:boolean;booked:boolean;mature:boolean;variant:string;company:string;industry:string;location:string;wordBand:string;day:string};
export function outcomes(w:Workspace,now=Date.now(),rangeDays=90):Outcome[]{const permitted=(s?:boolean)=>w.demo?true:!s;const sends=w.messages.filter(m=>permitted(m.synthetic)&&m.sequence===0&&m.sentAt&&Number.isFinite(Date.parse(m.sentAt))&&Date.parse(m.sentAt)<=now&&['sent','bounced','replied'].includes(m.state)).sort((a,b)=>a.sentAt!.localeCompare(b.sentAt!)||a.id.localeCompare(b.id));const seen=new Set<string>();return sends.filter(m=>{if(seen.has(m.contactId))return false;seen.add(m.contactId);return true}).filter(m=>Date.parse(m.sentAt!)>=now-rangeDays*DAY).map(m=>{const start=Date.parse(m.sentAt!),end=start+14*DAY,c=w.contacts.find(c=>c.id===m.contactId);const seenReplies=new Set<string>();const replies=w.conversations.filter(r=>permitted(r.synthetic)&&r.messageId===m.id&&r.contactId===m.contactId&&r.reviewed&&Date.parse(r.receivedAt)>=start&&Date.parse(r.receivedAt)<=Math.min(now,end)).filter(r=>{const key=r.providerId||r.id;if(seenReplies.has(key))return false;seenReplies.add(key);return true});const words=m.body.trim().split(/\s+/).length;let day='Unknown';try{if(!m.recipientTimezone)throw Error('Unknown timezone');day=new Intl.DateTimeFormat('en',{timeZone:m.recipientTimezone,weekday:'long'}).format(new Date(start));}catch{}return {message:m,replies,human:replies.some(r=>HUMAN.has(r.classification)),positive:replies.some(r=>r.classification==='Interested'),declined:replies.some(r=>r.classification==='Declined'),optout:replies.some(r=>r.classification==='Opt-out'),bounce:m.state==='bounced',booked:w.meetings.some(x=>permitted(x.synthetic)&&x.contactId===m.contactId&&x.createdAt&&Date.parse(x.createdAt)>=start&&Date.parse(x.createdAt)<=Math.min(now,end)&&['Upcoming','Completed'].includes(x.state)),mature:end<=now,variant:m.variant||'Untracked / edited',company:m.companyAtSend||'Unknown (no send snapshot)',industry:m.industryAtSend||'Unknown (no send snapshot)',location:m.locationAtSend||'Unknown (no send snapshot)',wordBand:words<80?'Under 80':words<=130?'80–130':'Over 130',day};});}
export function summary(rows:Outcome[]){const n=rows.length,positive=rows.filter(r=>r.positive).length;return {n,human:rows.filter(r=>r.human).length,positive,declined:rows.filter(r=>r.declined).length,optouts:rows.filter(r=>r.optout).length,bounces:rows.filter(r=>r.bounce).length,booked:rows.filter(r=>r.booked).length,interval:wilson(positive,n),posteriorMean:(positive+1)/(n+2)};}
export function segments(rows:Outcome[],key:'variant'|'company'|'industry'|'location'|'wordBand'|'day'){const groups=new Map<string,Outcome[]>();rows.forEach(r=>groups.set(r[key],[...(groups.get(r[key])||[]),r]));return [...groups].map(([label,items])=>({label,...summary(items)})).sort((a,b)=>b.n-a.n);}
export function learningRecommendation(w:Workspace,now=Date.now()){const rows=outcomes(w,now).filter(r=>r.mature);const groups=VARIANTS.map(v=>({variant:v,...summary(rows.filter(r=>r.variant===v))}));const sorted=[...groups].sort((a,b)=>b.posteriorMean-a.posteriorMean);const supported=groups.every(g=>g.n>=30)&&sorted[0].interval.low>sorted[1].interval.high;return {groups,supported,preferred:supported?sorted[0].variant:null,reason:supported?'One approach has stronger observed results. This is an association, not proof of causation; retain a comparison group.':'Keep comparing both approaches. Need at least 30 mature contacts per approach and separated uncertainty intervals before preferring one.'};}
export function chooseVariant(w:Workspace,now=Date.now(),random=Math.random()){const result=learningRecommendation(w,now);const variant=result.preferred?(random<.8?result.preferred:VARIANTS.find(v=>v!==result.preferred)!):VARIANTS[random<.5?0:1];return {variant,learningVersion:'bayesian-response-v1',learningReason:result.reason,assignment:result.preferred?'80/20 observational preference':'50/50 randomized exploration'};}
