import type { Contact, Message, Settings } from './types';
export function normalizedEmail(s:string){return s.trim().toLowerCase();}
export function emailIdentity(s:string){const e=normalizedEmail(s);const [local,domain]=e.split('@');return ['gmail.com','googlemail.com'].includes(domain)?`${local.split('+')[0].replaceAll('.','')}@gmail.com`:e;}
/** Public profile identity only; names and employers are not unique identities. */
export function canonicalLinkedin(raw:string){
 try{
  const u=new URL(raw.trim());
  if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.port||! /^(?:www\.|m\.|[a-z]{2,3}\.)?linkedin\.com$/i.test(u.hostname))return '';
  const slug=u.pathname.match(/^\/in\/([a-z0-9_%~-]+)(?:\/|$)/i)?.[1];
  if(!slug)return '';
  const normalized=slug.toLowerCase().replace(/%([0-9a-f]{2})/g,(escape,hex)=>{const c=String.fromCharCode(parseInt(hex,16));return /^[a-z0-9_~-]$/i.test(c)?c.toLowerCase():escape;});
  return `https://www.linkedin.com/in/${normalized}`;
 }catch{return '';}
}
export function identitiesFor(c:Partial<Contact>){const linkedin=canonicalLinkedin(c.linkedin||'');return [...new Set([c.email,...(c.alternateEmails||[])].filter(e=>Boolean(e?.trim())).map(e=>'email:'+emailIdentity(e!)).concat(linkedin?['linkedin:'+linkedin]:[]))];}
export function normalizeAlternateEmails(raw:unknown){
 let input=raw;
 if(typeof input==='string')input=input.trim().startsWith('[')?JSON.parse(input):input.split(/[;,\n]/);
 if(input===undefined||input===null||input==='')return [];
 if(!Array.isArray(input))throw Error('Alternate emails must be a list.');
 const emails=[...new Set(input.map((x:unknown)=>normalizedEmail(String(x))).filter(Boolean))];
 if(emails.length>30||emails.some(e=>!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)))throw Error('Enter at most 30 valid alternate emails.');
 return emails;
}
export function safeUrl(s:string){try {const u=new URL(s);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}}
export function csvCell(value:unknown){let s=String(value??'');if(/^[\s]*[=+@\-\t\r]/.test(s)) s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
export function csv(rows:Record<string,unknown>[]){if(!rows.length)return '';const headers=Object.keys(rows[0]);return [headers.map(csvCell).join(','),...rows.map(r=>headers.map(h=>csvCell(r[h])).join(','))].join('\r\n');}
export function parseCsv(input:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<input.length;i++){const c=input[i];if(c==='"'){if(quoted&&input[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&input[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV contains an unclosed quote.');if(cell||row.length){row.push(cell);rows.push(row);}const headers=rows.shift()?.map(h=>h.trim().toLowerCase().replace(/^\uFEFF/,''))||[];return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])));}
export function reviewReasons(c:Contact,now=Date.now()){const reasons:string[]=[];if(c.synthetic)reasons.push('Demonstration contact');if(c.excluded)reasons.push('Excluded from outreach');if(!c.identityConfirmed)reasons.push('Identity needs confirmation');if(c.verification!=='valid')reasons.push('Email verification is inconclusive');if(!['published','authorized provider'].includes(c.emailOrigin))reasons.push('Email source needs review');if(!c.verifiedAt||!Number.isFinite(Date.parse(c.verifiedAt))||now-Date.parse(c.verifiedAt)>30*86400000)reasons.push('Verification is missing or stale');if(!c.sources.length||c.sources.some(s=>!safeUrl(s.url)||!Number.isFinite(Date.parse(s.retrievedAt))||now-Date.parse(s.retrievedAt)>90*86400000))reasons.push('Research is missing or stale');if(!c.fit||!c.topic)reasons.push('Personalization needs evidence');if(!c.timezone)reasons.push('Recipient time zone unknown');return reasons;}
export function sendReasons(c:Contact,m:Message,s:Settings,context:{authorized:boolean;approved?:boolean;provider:boolean;replyFresh:boolean;replied:boolean;booked:boolean;daily:number;weekly:number;company:number;now?:number}){const r=reviewReasons(c,context.now);if(!context.authorized)r.push('Pilot not approved');if(!context.approved)r.push('Exact email version is waiting for your approval');if(s.paused||!s.sending)r.push('Sending is paused');if(!context.provider)r.push('Email account disconnected');if(!context.replyFresh)r.push('Reply monitoring is stale');if(context.replied||context.booked)r.push('Reply or meeting stops this sequence');if(context.daily>=s.dailyCap||context.weekly>=s.weeklyCap||(s.companyCap>0&&context.company>=s.companyCap))r.push('Sending limit reached');if(!['draft','waiting_approval','queued'].includes(m.state))r.push('Message already submitted or not sendable');if(/[\[\]{}<>]/.test(m.body)||!m.subject.trim()||!m.body.trim())r.push('Unresolved placeholder or empty message');return r;}
export function draft(c:Contact,s:Settings,variant="workflow-question"){if(!s.name||!s.intro||!s.goal)throw Error('Add your name, introduction, and learning goal in Settings first.');if(!c.topic||!c.fit||!c.sources.length)throw Error('Add a specific topic, reason for fit, and supporting source before drafting.');return {subject:`A conversation about ${c.topic.slice(0,65)}`,body:`Hi ${c.name.split(' ')[0]},\n\n${s.intro}${s.experience ? ` ${s.experience}` : ''}\n\n${c.fit} I’m hoping to learn ${s.goal}. In particular, I’d love to hear your perspective on ${c.topic}. Your experience would help me understand how this works in practice and what someone exploring the field should pay attention to.\n\n${variant==='career-lesson'?'Looking back, which early-career experience best prepared you for the work you do today?':'If you’re open to sharing, what is one part of your day-to-day work that someone exploring the field might not expect?'} I’d appreciate any perspective you have, and completely understand if you’re busy.\n\n${s.signature||s.name}`};}
export function businessWindow(iso:string,zone:string,holidays:string[]=[]){try{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return !['Sat','Sun'].includes(p.weekday)&&+p.hour>=9&&+p.hour<17&&!holidays.includes(`${p.year}-${p.month}-${p.day}`);}catch{return false;}}
