import {supabase} from './supabase';
import {defaults,type Workspace,type Contact} from './types';
import {identitiesFor} from './safety';
import {discoveryStatus} from './discovery-job';
function check(error:any){if(error)throw Error(error.code==='23505'?'This identity already exists or is suppressed.':error.message||'Database unavailable. Your changes have not been saved.');}
export async function list(owner:string,kind:string){const client=await supabase();const rows:any[]=[];for(let offset=0;;offset+=1000){const {data,error}=await client.from('records').select('id,data,version').eq('owner',owner).eq('kind',kind).order('updated',{ascending:false}).order('id').range(offset,offset+999);check(error);rows.push(...(data||[]).map(r=>({...r.data,id:r.id,version:r.version})));if(!data||data.length<1000)break;if(rows.length>=20000)throw Error('Workspace is too large for this view. Export and archive old records.');}return rows;}
export async function get(owner:string,id:string,kind:string){const {data,error}=await (await supabase()).from('records').select('id,data,version').eq('owner',owner).eq('id',id).eq('kind',kind).single();check(error);if(!data)throw Error('Record not found.');return {...data.data,id:data.id,version:data.version};}
export function eventStatement(owner:string,type:string,data:unknown){return {async run(){const result=await (await supabase()).from('events').insert({owner,type,data});check(result.error);return result;}};}
export async function save(owner:string,kind:string,value:any){const {data,error}=await (await supabase()).rpc('save_record',{p_owner:owner,p_kind:kind,p_id:value.id||crypto.randomUUID(),p_version:value.version||null,p_data:value});check(error);return data as string;}
export async function contactSave(owner:string,value:Contact){const {data,error}=await (await supabase()).rpc('save_contact',{p_owner:owner,p_id:value.id||crypto.randomUUID(),p_version:value.version||null,p_data:value,p_keys:identitiesFor(value)});check(error);return data as string;}
export async function identityExists(owner:string,keys:string[]){if(!keys.length)return false;const {data,error}=await (await supabase()).from('identities').select('identity').eq('owner',owner).in('identity',keys).limit(1);check(error);return Boolean(data?.length);}
export async function workspace(owner:string):Promise<Workspace>{const client=await supabase();const [contacts,messages,meetings,conversations,settings,result,history]=await Promise.all([list(owner,'contact'),list(owner,'message'),list(owner,'meeting'),list(owner,'conversation'),list(owner,'settings'),client.from('events').select('*').eq('owner',owner).order('created',{ascending:false}).limit(150),client.rpc('outreach_status',{p_owner:owner})]);check(result.error);check(history.error);const locked=new Set((history.data||[]).map((r:{contact_id:string})=>r.contact_id));return {contacts:contacts.map(c=>({...c,outreachLocked:locked.has(c.id)})),messages,meetings,conversations,settings:{...defaults,...settings[0]},events:result.data||[],discovery:await discoveryStatus(client,owner,settings[0]?.discovery===true)};}
/** A database transaction reserves all known identities before a Gmail URL is released. */
export async function reserveOutreach(owner:string,message:{id:string;version?:number},contact:{version?:number},mode:'prepare'|'record_sent',sentAt?:string){const {error}=await (await supabase()).rpc('reserve_outreach',{p_owner:owner,p_message_id:message.id,p_version:message.version,p_contact_version:contact.version,p_mode:mode,p_sent_at:sentAt||null});check(error);}
export async function stopContact(owner:string,id:string,reason:string,remove=false){const {error}=await (await supabase()).rpc('stop_contact',{p_owner:owner,p_id:id,p_reason:reason,p_remove:remove});check(error);}
