import {allowedCompany,TARGET_COMPANIES} from '@/lib/company-scope';
import {isSalesAndTrading} from '@/lib/targeting';
import {gmailComposeUrl} from '@/lib/gmail-compose';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {workspace,save,get,contactSave,identityExists,stopContact,eventStatement,list,reserveOutreach} from '@/lib/store';
import {csv,draft,parseCsv,safeUrl,canonicalLinkedin,canonicalPublicProfile,normalizedEmail,normalizeAlternateEmails,identitiesFor} from '@/lib/safety';
import {analyzeReply,chooseVariant,CLASSES} from '@/lib/learning';
import {defaults,type Contact} from '@/lib/types';
import {discoveryConfig} from '@/lib/discovery-job';
import {contactFromHitlRow,hitlTemplateCsv,hitlWorksheetCsv,validateHitlIdentity} from '@/lib/hitl-intake';
import {enrichHunterFoundEmail} from '@/lib/hunter-enrichment';
export const dynamic='force-dynamic';
export const maxDuration=60;
const json=(x:unknown,status=200)=>Response.json(x,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:Request){const user=await getChatGPTUser();if(!user)return json({error:'Sign in to access your workspace.'},401);try{const format=new URL(req.url).searchParams.get('export');if(format==='hitl-template')return new Response(hitlTemplateCsv(),{headers:{'Content-Type':'text/csv;charset=utf-8','Content-Disposition':'attachment; filename="sales-trading-hitl-template.csv"','Cache-Control':'no-store'}});if(format==='hitl-worksheet')return new Response(hitlWorksheetCsv(),{headers:{'Content-Type':'text/csv;charset=utf-8','Content-Disposition':'attachment; filename="sales-trading-75-contact-worksheet.csv"','Cache-Control':'no-store'}});const data=await workspace(user.userId);if(format==='backup')return new Response(JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),...data},null,2),{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="common-ground-backup.json"','Cache-Control':'no-store'}});if(format){const rows=format==='messages'?data.messages.map(m=>({...m,contactName:data.contacts.find(c=>c.id===m.contactId)?.name||''})):format==='meetings'?data.meetings:data.contacts.map(c=>({...c,sources:JSON.stringify(c.sources),alternateEmails:JSON.stringify(c.alternateEmails||[])}));return new Response(csv(rows),{headers:{'Content-Type':'text/csv;charset=utf-8','Content-Disposition':`attachment; filename="${['messages','meetings'].includes(format)?format:'contacts'}.csv"`,'Cache-Control':'no-store'}});}return json({...data,enrichment:{configured:Boolean(process.env.HUNTER_API_KEY),provider:'Hunter',note:process.env.HUNTER_API_KEY?'Email verification is ready. The server accepts only found, valid, non-catch-all company addresses.':'Add HUNTER_API_KEY to the Vercel project once; the website will then verify and import reviewed rows automatically.'}});}catch{return json({error:'The database is unavailable. Retry shortly; existing records remain stored.'},503);}}
export async function POST(req:Request){const user=await getChatGPTUser();if(!user)return json({error:'Sign in to access your workspace.'},401);const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)return json({error:'Request origin rejected.'},403);try{const raw=await req.text();if(raw.length>500000)return json({error:'Upload is too large. Use at most 100 rows.'},413);const {action,payload={}}=JSON.parse(raw);const owner=user.userId;
if(action==='saveContact'){const c=validateContact(payload);await contactSave(owner,c);}
else if(action==='import'){const rows=parseCsv(String(payload.csv||''));if(!rows.length||rows.length>100)throw Error('Import between 1 and 100 rows.');let added=0,duplicates=0;const issues:string[]=[];for(let i=0;i<rows.length;i++){try{await contactSave(owner,contactFromHitlRow(rows[i]));added++;}catch(e){const message=(e as Error).message;if(/identity already exists|matching record already exists|already exists or is suppressed/i.test(message))duplicates++;else issues.push(`Row ${i+2}: ${message}`);}}return json({added,duplicates,rejected:issues.length,issues});}
else if(action==='enrichAndImport'){const key=process.env.HUNTER_API_KEY;if(!key)throw Error('Hunter is not connected. Add HUNTER_API_KEY to the Vercel project, then redeploy once.');const row=payload.row as Record<string,string>;const identity=validateHitlIdentity(row);if(await identityExists(owner,identitiesFor({linkedin:identity.linkedin,profileUrl:identity.profileUrl})))throw Error('This person is already in lifetime history.');const enriched=await enrichHunterFoundEmail(row,key);const contact=contactFromHitlRow(enriched);await contactSave(owner,contact);return json({ok:true,name:contact.name,company:contact.company,email:contact.email});}
else if(action==='draft'){const c=await get(owner,payload.id,'contact');if(!isSalesAndTrading(c)||!allowedCompany(c.company))throw Error('Outreach is restricted to Sales & Trading at your 15 approved companies.');if(c.excluded)throw Error('This contact is suppressed.');const w=await workspace(owner);if(w.messages.some(m=>m.contactId===c.id&&m.state!=='cancelled'))throw Error('An email already exists for this person. Review it in Outbox.');const choice=w.settings.emailTemplate?{variant:'User template',assignment:'Owner-selected template',learningReason:'Personalized from confirmed desk and product evidence; not an A/B experiment.'}:chooseVariant(w);const d=draft(c,w.settings,choice.variant);await save(owner,'message',{...d,...choice,contactId:c.id,state:'waiting_approval',scheduledAt:'',sequence:0,synthetic:false});}
else if(action==='prepareGmail'){const m=await get(owner,payload.id,'message');if(m.gmailPreparedAt)throw Error('This email has already been opened in Gmail. Check Gmail Drafts or Sent; another handoff is permanently blocked.');if(m.version!==payload.version)throw Error('This draft changed. Refresh and review it again.');if(payload.approved!==true)throw Error('Review and approve the exact email first.');const c=await get(owner,m.contactId,'contact');if(!isSalesAndTrading(c)||!allowedCompany(c.company))throw Error('Outreach is restricted to Sales & Trading at your 15 approved companies.');if(c.version!==payload.contactVersion)throw Error('This contact changed. Refresh and review the recipient again.');if(c.verification!=='valid'&&payload.acceptPublishedAddress!==true)throw Error('This published address has not been deliverability-tested. Confirm your review before opening Gmail.');const url=gmailComposeUrl(c,m,process.env.OWNER_EMAIL!);await reserveOutreach(owner,m,c,'prepare');return json({url});}
else if(action==='saveMessage'){const m=await get(owner,payload.id,'message');if(!['draft','waiting_approval','held'].includes(m.state)||m.gmailPreparedAt)throw Error('Prepared and sent emails cannot be edited. Check Gmail Drafts or Sent.');await save(owner,'message',{...m,version:payload.version,state:'waiting_approval',variant:(payload.subject===m.subject&&payload.body===m.body)?m.variant:'Untracked / edited',subject:String(payload.subject||'').slice(0,200),body:String(payload.body||'').slice(0,10000)});}
else if(action==='messageState'){const m=await get(owner,payload.id,'message');if(!['draft','waiting_approval','held','queued'].includes(m.state))throw Error('Submitted and sent messages are immutable.');if(!['held','cancelled','draft'].includes(payload.state))throw Error('Scheduling requires connected email, monitoring, and an approved pilot.');await save(owner,'message',{...m,state:payload.state});}
else if(action==='settings'){const old=(await list(owner,'settings'))[0];const p={emailTemplate:'',salesParagraph:'',tradingParagraph:'',...defaults,...payload};p.approvalRequired=true;p.callMinutes=15;p.sending=false;p.discovery=payload.discovery===true;const discovery=discoveryConfig();if(p.discovery&&(!discovery.enabled||!discovery.configured))throw Error('Configure and enable the approved discovery provider on the server before activating daily research.');p.followups=false;p.drafting=false;p.paused=true;p.targets=TARGET_COMPANIES.join(', ');p.dailyCap=50;p.weeklyCap=350;p.companyCap=4;for(const k of ['emailTemplate','salesParagraph','tradingParagraph','name','intro','experience','interests','goal','linkedin','resume','projects','signature','timezone','availability','bookingUrl','targets','exclusions','regions']){if(typeof p[k]!=='string'||p[k].length>10000)throw Error('Settings contain invalid text.');}for(const k of ['linkedin','resume','bookingUrl'])if(p[k]&&!safeUrl(p[k]))throw Error('Links must use https.');try{new Intl.DateTimeFormat('en',{timeZone:p.timezone});}catch{throw Error('Enter a valid time zone such as America/Chicago.');}if(!Number.isFinite(p.monthlyBudget)||p.monthlyBudget<0||p.monthlyBudget>10000)throw Error('Monthly budget must be a non-negative number.');await save(owner,'settings',{...p,id:old?.id,version:old?.version});}
else if(action==='pause'){const old=(await list(owner,'settings'))[0];await save(owner,'settings',{...defaults,...old,paused:true,sending:false,followups:false,discovery:false,drafting:false});await eventStatement(owner,'All automation paused',{}).run();}
else if(action==='exclude'||action==='delete'){await stopContact(owner,payload.id,String(payload.reason||'Excluded by owner'),action==='delete');}
else if(action==='meeting'){const c=await get(owner,payload.contactId,'contact');const current=payload.id?await get(owner,payload.id,'meeting'):null;if(!['Upcoming','Completed','Cancelled','No-show'].includes(payload.state))throw Error('Invalid meeting outcome.');if(!Number.isFinite(Date.parse(payload.start)))throw Error('Choose a valid date and time.');await save(owner,'meeting',{id:current?.id,version:current?.version,contactId:c.id,title:String(payload.title||`Conversation with ${c.name}`),start:payload.start,state:payload.state,notes:String(payload.notes||'').slice(0,10000),source:'manual',createdAt:current?.createdAt||new Date().toISOString()});for(const m of (await list(owner,'message')).filter(m=>m.contactId===c.id&&['draft','waiting_approval','queued','held'].includes(m.state)))await save(owner,'message',{...m,state:'cancelled'});}
else if(action==='recordSent'){const m=await get(owner,payload.id,'message');if(!['draft','waiting_approval','held'].includes(m.state))throw Error('Only an unsent draft can be recorded as sent.');if(payload.confirmed!==true)throw Error('Confirm that this exact email was already sent by you.');const at=Date.parse(payload.sentAt);if(!Number.isFinite(at)||at>Date.now())throw Error('Enter the actual past send time.');const c=await get(owner,m.contactId,'contact');await reserveOutreach(owner,m,c,'record_sent',new Date(at).toISOString());}
else if(action==='reply'||action==='reviewReply'){const c=await get(owner,payload.contactId,'contact');const previous=action==='reviewReply'?await get(owner,payload.id,'conversation'):null;if(previous&&previous.contactId!==c.id)throw Error('Reply does not belong to this contact.');if(!CLASSES.includes(payload.classification))throw Error('Choose a reply classification.');const body=String(payload.body||previous?.body||'').slice(0,12000);if(!body.trim())throw Error('Enter the reply text.');const messageId=payload.messageId||previous?.messageId||'';const receivedAt=payload.receivedAt||previous?.receivedAt||new Date().toISOString();if(!Number.isFinite(Date.parse(receivedAt))||Date.parse(receivedAt)>Date.now())throw Error('Enter a valid past reply time.');if(messageId){const m=await get(owner,messageId,'message');if(m.contactId!==c.id||!m.sentAt||!['sent','replied','bounced'].includes(m.state)||Date.parse(receivedAt)<Date.parse(m.sentAt))throw Error('Choose a sent email to this contact that predates the reply.');}const suggestion=analyzeReply(body,(await list(owner,'conversation')).filter(r=>r.id!==previous?.id));await save(owner,'conversation',{...previous,contactId:c.id,body,classification:payload.classification,receivedAt,messageId,reviewed:true,suggestedClassification:previous?.suggestedClassification||suggestion.label,analysisMethod:previous?.analysisMethod||suggestion.method,analysisReason:previous?.analysisReason||suggestion.reason,source:'manual'});await eventStatement(owner,'Reply label reviewed',{replyId:previous?.id||null,classification:payload.classification,suggested:suggestion.label}).run();for(const m of (await list(owner,'message')).filter(m=>m.contactId===c.id&&['draft','waiting_approval','queued','held'].includes(m.state)))await save(owner,'message',{...m,state:'held'});if(['Declined','Opt-out'].includes(payload.classification))await stopContact(owner,c.id,payload.classification);}
else throw Error('This action is unavailable. No automation is active.');return json({ok:true});}catch(e){return json({error:(e as Error).message.includes('constraint')?'A matching record already exists. Refresh and review.':(e as Error).message},400);}}
function validateContact(p:any):Contact{const name=String(p.name||'').trim();const email=normalizedEmail(String(p.email||''));const linkedin=canonicalLinkedin(String(p.linkedin||''));const profileUrl=canonicalPublicProfile(String(p.profileUrl||''));if(p.linkedin&&!linkedin)throw Error('Use a valid public LinkedIn profile URL (linkedin.com/in/...).');if(p.profileUrl&&!profileUrl)throw Error('Use a unique HTTPS public profile URL.');const alternateEmails=normalizeAlternateEmails(p.alternateEmails??p.alternateemails);if(!name||name.length>200)throw Error('A full name is required (maximum 200 characters).');if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Enter a valid email.');const sources=Array.isArray(p.sources)?p.sources.slice(0,20).map((s:any)=>({url:safeUrl(String(s.url||'')),note:String(s.note||'').slice(0,3000),retrievedAt:String(s.retrievedAt||'')})):[];if(sources.some((s:any)=>!s.url))throw Error('Source URLs must use https.');const contact:Contact={id:typeof p.id==='string'?p.id:'',version:p.version,name,email,desk:['sales','trading'].includes(p.desk)?p.desk:'',productGroup:String(p.productGroup||'').slice(0,200),deskEvidence:String(p.deskEvidence||'').slice(0,3000),title:String(p.title||'').slice(0,300),company:String(p.company||'').slice(0,300),industry:String(p.industry||''),location:String(p.location||''),linkedin,profileUrl,alternateEmails,timezone:String(p.timezone||''),status:String(p.status||'Research needed'),verification:['valid','invalid','catch-all','unknown'].includes(p.verification)?p.verification:'unknown',verifiedAt:String(p.verifiedAt||''),emailOrigin:['published','authorized provider','inferred','unknown'].includes(p.emailOrigin)?p.emailOrigin:'unknown',identityConfirmed:p.identityConfirmed===true,fit:String(p.fit||'').slice(0,3000),topic:String(p.topic||'').slice(0,1000),notes:String(p.notes||'').slice(0,10000),sources,excluded:p.excluded===true,synthetic:false};if(!isSalesAndTrading(contact)||!allowedCompany(contact.company))throw Error('Only documented Sales & Trading professionals at the 15 approved companies are allowed.');return contact;}
